# Generated by Django 5.2 on 2025-07-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
