# Generated by Django 5.2 on 2025-07-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_audiobook_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='genre',
            field=models.CharField(choices=[('', 'Select Genre Based on Mood'), ('Feel-Good Fiction', 'Feel-Good Fiction'), ('Humor', 'Humor'), ('Inspiration', 'Inspiration'), ('Self-Help', 'Self-Help'), ('Romantic Comedy', 'Romantic Comedy'), ('Philosophy', 'Philosophy'), ('Psychology', 'Psychology'), ('Biography', 'Biography'), ('Spirituality', 'Spirituality'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Coming-of-Age', 'Coming-of-Age'), ('Tragedy', 'Tragedy'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Adventure', 'Adventure'), ('Dystopian', 'Dystopian'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Detective', 'Detective Fiction'), ('True Crime', 'True Crime'), ('Horror', 'Horror'), ('Dark Fantasy', 'Dark Fantasy'), ('Supernatural', 'Supernatural'), ('Non-Fiction', 'Non-Fiction'), ('History', 'History'), ('Science & Tech', 'Science & Tech'), ('Productivity', 'Productivity'), ('Business', 'Business'), ('Short Stories', 'Short Stories'), ('Poetry', 'Poetry'), ('Children', 'Children'), ('Young Adult', 'Young Adult'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
    ]
